//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call_ItemsUsed
    {
        public int ItemsUsed_ID { get; set; }
        public int Call_ID { get; set; }
        public int Inventory_ID { get; set; }
        public Nullable<int> ItemsUsed_Qty { get; set; }
    
        public virtual Call Call { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
