//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.Interviews = new HashSet<Interview>();
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int Candidate_ID { get; set; }
        public string Candidate_Name { get; set; }
        public string Candidate_Surname { get; set; }
        public string Candidate_Email { get; set; }
        public string Candidate_ContactNumber { get; set; }
        public byte[] Candidate_CVFile { get; set; }
    
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<JobApplication> JobApplications { get; set; }
    }
}
