//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistItem()
        {
            this.ItemsChecklists = new HashSet<ItemsChecklist>();
        }
    
        public int ChecklistItem_ID { get; set; }
        public int ChecklistItemType_ID { get; set; }
        public string ChecklistItem_Description { get; set; }
        public Nullable<bool> ChecklistItem_ComplianceValue { get; set; }
    
        public virtual ChecklistItemType ChecklistItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsChecklist> ItemsChecklists { get; set; }
    }
}
