//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistItemType
    {
        public ChecklistItemType()
        {
            this.ChecklistItems = new HashSet<ChecklistItem>();
        }
    
        public int ChecklistItemType_ID { get; set; }
        public string ChecklistItemType_Description { get; set; }
    
        public virtual ICollection<ChecklistItem> ChecklistItems { get; set; }
    }
}
