//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        public Checklist()
        {
            this.ItemsChecklists = new HashSet<ItemsChecklist>();
            this.VehicleTypes = new HashSet<VehicleType>();
        }
    
        public int Checklist_ID { get; set; }
        public string Checklist_Name { get; set; }
    
        public virtual ICollection<ItemsChecklist> ItemsChecklists { get; set; }
        public virtual ICollection<VehicleType> VehicleTypes { get; set; }
    }
}
