//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Interviews = new HashSet<Interview>();
            this.Shifts = new HashSet<Shift>();
            this.StockTakes = new HashSet<StockTake>();
            this.VehicleCalls = new HashSet<VehicleCall>();
            this.Written_OffInventory = new HashSet<Written_OffInventory>();
            this.QualificationTypes = new HashSet<QualificationType>();
            this.RoleTypes = new HashSet<RoleType>();
        }
    
        public int Employee_ID { get; set; }
        public int EmployeeTitle_ID { get; set; }
        public int SecurityQuestion_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Surname { get; set; }
        public string Employee_IDNumber { get; set; }
        public string Employee_ContactNumber { get; set; }
        public string Employee_EmailAddress { get; set; }
        public string Employee_HashedPassword { get; set; }
        public string Employee_SecurityQuestionAnswer { get; set; }
        public string Employee_SARSTaxNumber { get; set; }
        public byte[] Employee_Signature { get; set; }
    
        public virtual EmployeeTitle EmployeeTitle { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual ICollection<StockTake> StockTakes { get; set; }
        public virtual ICollection<VehicleCall> VehicleCalls { get; set; }
        public virtual ICollection<Written_OffInventory> Written_OffInventory { get; set; }
        public virtual ICollection<QualificationType> QualificationTypes { get; set; }
        public virtual ICollection<RoleType> RoleTypes { get; set; }
    }
}
