//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullCall
    {
        public int Call_ID { get; set; }
        public int CallStatus_ID { get; set; }
        public int Reason_ID { get; set; }
        public Nullable<System.DateTime> Call_Date { get; set; }
        public Nullable<System.TimeSpan> Call_StartTime { get; set; }
        public Nullable<System.TimeSpan> Call_EndTime { get; set; }
        public Nullable<int> DOA_Number { get; set; }
        public Nullable<int> PRF_Number { get; set; }
        public string Reason_Description { get; set; }
        public string CallStatus_Description { get; set; }
        public int Employee_ID { get; set; }
        public string Employee_Surname { get; set; }
    }
}
