//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullVehicleInventory
    {
        public int Inventory_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public Nullable<int> MinimumQty { get; set; }
        public Nullable<int> MaximumQty { get; set; }
        public Nullable<int> VehicleInventory_Qty { get; set; }
        public string Inventory_Name { get; set; }
        public int Employee_ID { get; set; }
        public int Call_ID { get; set; }
    }
}
