//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionType
    {
        public InspectionType()
        {
            this.VehicleInspections = new HashSet<VehicleInspection>();
        }
    
        public int InspectionType_ID { get; set; }
        public string InspectionType_Description { get; set; }
    
        public virtual ICollection<VehicleInspection> VehicleInspections { get; set; }
    }
}
