//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewType
    {
        public InterviewType()
        {
            this.Interviews = new HashSet<Interview>();
        }
    
        public int InterviewType_ID { get; set; }
        public string InterviewType_Description { get; set; }
    
        public virtual ICollection<Interview> Interviews { get; set; }
    }
}
