//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int Interview_ID { get; set; }
        public int Candidate_ID { get; set; }
        public int InterviewType_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> ScheduledDate_Time { get; set; }
        public string InterviewMethod { get; set; }
        public string Address { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual InterviewType InterviewType { get; set; }
    }
}
