//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int Candidate_ID { get; set; }
        public int Position_ID { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<bool> Shortlisted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual JobPosition JobPosition { get; set; }
    }
}
