//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleType
    {
        public RoleType()
        {
            this.JobPositions = new HashSet<JobPosition>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int RoleType_ID { get; set; }
        public string RoleType_Description { get; set; }
    
        public virtual ICollection<JobPosition> JobPositions { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
