//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTake
    {
        public StockTake()
        {
            this.StockTakeTotals = new HashSet<StockTakeTotal>();
        }
    
        public int StockTake_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> StockTake_DateTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<StockTakeTotal> StockTakeTotals { get; set; }
    }
}
