//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInspection()
        {
            this.InspectionChecklists = new HashSet<InspectionChecklist>();
        }
    
        public int Inspection_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public int InspectionType_ID { get; set; }
        public Nullable<System.DateTime> Inspection_Date { get; set; }
        public string Inspector_Name { get; set; }
        public string Inspector_Surname { get; set; }
        public Nullable<int> Inspection_ComplianceScore { get; set; }
        public string Inspection_Comments { get; set; }
        public Nullable<bool> Passed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectionChecklist> InspectionChecklists { get; set; }
        public virtual InspectionType InspectionType { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
