//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public VehicleType()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int VehicleType_ID { get; set; }
        public int Checklist_ID { get; set; }
        public string VehicleType_Description { get; set; }
    
        public virtual Checklist Checklist { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
