//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Written_OffInventory
    {
        public int Write_Off_ID { get; set; }
        public int Inventory_ID { get; set; }
        public int Write_OffReason_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> Write_Off_Date { get; set; }
        public Nullable<int> Write_Off_Qty { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Write_OffReason Write_OffReason { get; set; }
    }
}
