//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.Barcodes = new HashSet<Barcode>();
            this.Call_ItemsUsed = new HashSet<Call_ItemsUsed>();
            this.OrderLines = new HashSet<OrderLine>();
            this.PriceHistories = new HashSet<PriceHistory>();
            this.StockTakeTotals = new HashSet<StockTakeTotal>();
            this.VehicleInventories = new HashSet<VehicleInventory>();
            this.Written_OffInventory = new HashSet<Written_OffInventory>();
        }
    
        public int Inventory_ID { get; set; }
        public int InventoryType_ID { get; set; }
        public string Inventory_Name { get; set; }
        public Nullable<decimal> Inventory_LatestPrice { get; set; }
        public Nullable<int> Inventory_BaseCampQty { get; set; }
        public Nullable<int> Inventory_DaysToExpire { get; set; }
        public byte[] Inventory_Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Barcode> Barcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Call_ItemsUsed> Call_ItemsUsed { get; set; }
        public virtual InventoryType InventoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTakeTotal> StockTakeTotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInventory> VehicleInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Written_OffInventory> Written_OffInventory { get; set; }
    }
}
