//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediStockAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeTotal
    {
        public int Inventory_ID { get; set; }
        public int StockTake_ID { get; set; }
        public Nullable<int> StockTakeTotal_Qty { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual StockTake StockTake { get; set; }
    }
}
